### ISSUE TITLE
Add talk "Head first with vim specific helpfile" on the agenda

### ISSUE THREAD

**Issue by wikimatze** [vimberlin/vimfest#6]

**Comment by WolfgangMehner** [comment]
Hi. I'm listed as a speaker, but my talk seems to be missing.

Looking forward to Vimfest.

**Comment by wikimatze** [comment]
Oh, your talk would fit in the qa-session between 18:00 - 19:00 => would this be fine for you?

**Comment by WolfgangMehner** [comment]
Sounds good.
